spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cineinfo00@gmail.com
    password: ietocgrpttceootz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true