spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: lmhtest
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0